# Baseline 3.yml

model:
  num_classes: 9 
  num_clases_label: ["Waiting", "Setting", "Digging", "Falling", "Spiking", "Blocking", "Jumping", "Moving", "Standing"]

training:
  batch_size: 32
  learning_rate: 0.0001 #1e-4
  epochs: 10
  optimizer: "AdamW"
  weight_decay: 1

data:
  dataset_name: "GroupActivityDataset"
  data_dir: "data"
  annot_path: "data/annot_all.pkl"
  videos_path: "data/videos"

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

experiment:
  name: "Baseline_B3_step_A"
  version: 1
  seed: 31
  output_dir: "outputs"
  description: "Phase one train person action classifier"
